/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marlonenathan.telas;

/**
 *
 * @author Nathan
 */
public class TelaEscolhaFuncionario extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form TelaCadastroDePacientes
	 */
	public TelaEscolhaFuncionario() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		btnCadastroPaciente = new javax.swing.JButton();
		btnAtendimento = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		btnSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Escolha Funcionario");
		setMaximumSize(new java.awt.Dimension(500, 400));
		setMinimumSize(new java.awt.Dimension(500, 400));
		setResizable(false);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(0, 102, 204));
		jPanel1.setMaximumSize(new java.awt.Dimension(500, 180));
		jPanel1.setMinimumSize(new java.awt.Dimension(500, 180));
		jPanel1.setPreferredSize(new java.awt.Dimension(400, 93));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/logo.png"))); // NOI18N

		jLabel1.setFont(new java.awt.Font("Noto Sans CJK KR Black", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Bem-vindo");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(44, 44, 44).addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
						.addComponent(jLabel1).addGap(37, 37, 37)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(21, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(63,
														63, 63))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
																132, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(27, 27, 27)))));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 180));

		jPanel2.setBackground(new java.awt.Color(40, 40, 40));
		jPanel2.setMaximumSize(new java.awt.Dimension(500, 43));
		jPanel2.setMinimumSize(new java.awt.Dimension(500, 43));
		jPanel2.setPreferredSize(new java.awt.Dimension(500, 43));

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Esolha um ambiente");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(188, Short.MAX_VALUE).addComponent(jLabel3).addGap(157, 157, 157)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3).addContainerGap()));

		getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 500, 40));

		jPanel3.setBackground(new java.awt.Color(8, 77, 110));
		jPanel3.setMaximumSize(new java.awt.Dimension(500, 180));
		jPanel3.setMinimumSize(new java.awt.Dimension(500, 180));
		jPanel3.setPreferredSize(new java.awt.Dimension(500, 179));

		btnCadastroPaciente.setBackground(new java.awt.Color(1, 152, 117));
		btnCadastroPaciente.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
		btnCadastroPaciente.setForeground(new java.awt.Color(255, 255, 255));
		btnCadastroPaciente.setText("Cadastro de Paciente");
		btnCadastroPaciente.setBorderPainted(false);
		btnCadastroPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnCadastroPaciente.setFocusPainted(false);
		btnCadastroPaciente.setMaximumSize(new java.awt.Dimension(185, 32));
		btnCadastroPaciente.setMinimumSize(new java.awt.Dimension(185, 32));
		btnCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCadastroPacienteActionPerformed(evt);
			}
		});

		btnAtendimento.setBackground(new java.awt.Color(255, 153, 0));
		btnAtendimento.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
		btnAtendimento.setForeground(new java.awt.Color(255, 255, 255));
		btnAtendimento.setText("Lista de atendimentos");
		btnAtendimento.setBorderPainted(false);
		btnAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnAtendimento.setFocusPainted(false);
		btnAtendimento.setMaximumSize(new java.awt.Dimension(220, 32));
		btnAtendimento.setMinimumSize(new java.awt.Dimension(220, 32));
		btnAtendimento.setPreferredSize(new java.awt.Dimension(220, 32));
		btnAtendimento.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtendimentoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 450,
										Short.MAX_VALUE))
						.addContainerGap(27, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(32, Short.MAX_VALUE)
						.addComponent(btnCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(btnAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(30, 30, 30)));

		getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 500, 180));

		jPanel4.setBackground(new java.awt.Color(8, 77, 110));
		jPanel4.setPreferredSize(new java.awt.Dimension(500, 85));

		btnSair.setBackground(new java.awt.Color(217, 81, 25));
		btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/delete.png"))); // NOI18N
		btnSair.setBorderPainted(false);
		btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSair.setFocusPainted(false);
		btnSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSairActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						.addContainerGap(408, Short.MAX_VALUE).addComponent(btnSair,
								javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout
						.createSequentialGroup().addContainerGap().addComponent(btnSair,
								javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(21, Short.MAX_VALUE)));

		getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 500, 80));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
		new TelaLogin().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnSairActionPerformed

	private void btnCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		new TelaCadastroDePacientes().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void btnAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		new TelaListaDeAtendimentos().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaEscolhaFuncionario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaEscolhaFuncionario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSair;
	private javax.swing.JButton btnCadastroPaciente;
	private javax.swing.JButton btnAtendimento;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	// End of variables declaration//GEN-END:variables
}
