/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marlonenathan.telas;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Rectangle;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import br.com.marlonenathan.model.bean.Atendimento;
import br.com.marlonenathan.model.dao.AtendimentoDAO;

/**
 *
 * @author marlonmazzine
 */
public final class TelaListaDeAtendimentos extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form TelaCadastroDeFuncionarios
	 */
	public TelaListaDeAtendimentos() {
		initComponents();
		DefaultTableModel modelo = (DefaultTableModel) tbAtendimentos.getModel();
		tbAtendimentos.setRowSorter(new TableRowSorter<DefaultTableModel>(modelo));

		readTable();
	}

	Atendimento a = new Atendimento();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		txtPesquisaPeloNome = new javax.swing.JTextField();
		btnPesquisar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tbAtendimentos = new javax.swing.JTable();
		btnVoltar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Lista de atendimentos");
		setBackground(new java.awt.Color(8, 77, 110));
		setMinimumSize(new java.awt.Dimension(1280, 720));
		setResizable(false);

		jPanel2.setBackground(new java.awt.Color(8, 77, 110));
		jPanel2.setMaximumSize(new java.awt.Dimension(1280, 720));
		jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
		jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));

		txtPesquisaPeloNome.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
		txtPesquisaPeloNome.setText("Nome do paciente");
		txtPesquisaPeloNome.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				txtPesquisaPeloNomeFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				txtPesquisaPeloNomeFocusLost(evt);
			}
		});

		btnPesquisar.setBackground(new java.awt.Color(153, 153, 153));
		btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		btnPesquisar.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/pesquisar.png"))); // NOI18N
		btnPesquisar.setBorderPainted(false);
		btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnPesquisar.setFocusPainted(false);
		btnPesquisar.setMaximumSize(new java.awt.Dimension(79, 40));
		btnPesquisar.setMinimumSize(new java.awt.Dimension(79, 40));
		btnPesquisar.setPreferredSize(new java.awt.Dimension(79, 40));
		btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPesquisarActionPerformed(evt);
			}
		});

		tbAtendimentos.setAutoCreateRowSorter(true);
		tbAtendimentos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
		tbAtendimentos.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null, null } },
				new String[] { "Nome", "SUS", "Data", "Nº do atendimento" }) {
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tbAtendimentos.setColumnSelectionAllowed(true);
		tbAtendimentos.setRowHeight(30);
		jScrollPane1.setViewportView(tbAtendimentos);
		tbAtendimentos.getColumnModel().getSelectionModel()
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		if (tbAtendimentos.getColumnModel().getColumnCount() > 0) {
			tbAtendimentos.getColumnModel().getColumn(1).setMinWidth(200);
			tbAtendimentos.getColumnModel().getColumn(1).setPreferredWidth(200);
			tbAtendimentos.getColumnModel().getColumn(1).setMaxWidth(200);
			tbAtendimentos.getColumnModel().getColumn(2).setMinWidth(110);
			tbAtendimentos.getColumnModel().getColumn(2).setPreferredWidth(110);
			tbAtendimentos.getColumnModel().getColumn(2).setMaxWidth(110);
			tbAtendimentos.getColumnModel().getColumn(3).setMinWidth(130);
			tbAtendimentos.getColumnModel().getColumn(3).setPreferredWidth(130);
			tbAtendimentos.getColumnModel().getColumn(3).setMaxWidth(130);
		}

		btnVoltar.setBackground(new java.awt.Color(255, 153, 0));
		btnVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
		btnVoltar
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/voltar.png"))); // NOI18N
		btnVoltar.setText("  Voltar");
		btnVoltar.setToolTipText("");
		btnVoltar.setBorderPainted(false);
		btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnVoltar.setFocusCycleRoot(true);
		btnVoltar.setFocusPainted(false);
		btnVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVoltarActionPerformed(evt);
			}
		});

		JButton btnVerAtendimento = new JButton();
		btnVerAtendimento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		btnVerAtendimento.setBounds(new Rectangle(0, 0, 100, 40));
		btnVerAtendimento.setToolTipText("");
		btnVerAtendimento.setText("Ver atendimento >>");
		btnVerAtendimento.setForeground(Color.WHITE);
		btnVerAtendimento.setFont(new Font("Dialog", Font.BOLD, 18));
		btnVerAtendimento.setFocusPainted(false);
		btnVerAtendimento.setFocusCycleRoot(true);
		btnVerAtendimento.setBorderPainted(false);
		btnVerAtendimento.setBackground(new Color(0, 204, 255));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap(38, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addComponent(txtPesquisaPeloNome, GroupLayout.PREFERRED_SIZE, 468,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18)
								.addComponent(btnPesquisar, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
										.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 145,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnVerAtendimento, GroupLayout.PREFERRED_SIZE, 386,
												GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 1215,
										GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(27, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addGap(36)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(txtPesquisaPeloNome, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnPesquisar, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
				.addGap(18).addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 505, GroupLayout.PREFERRED_SIZE)
				.addGap(18)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnVerAtendimento, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE))
				.addGap(33)));
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	String pesquisaPeloNome;

	private static final DateTimeFormatter FBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
	private static final LocalDate HOJE = LocalDate.now();
	private static final String DATA_ATENDIMENTO = HOJE.format(FBR);

	private void txtPesquisaPeloNomeFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtPesquisaPeloNomeFocusGained
		pesquisaPeloNome = txtPesquisaPeloNome.getText();
		if (pesquisaPeloNome.length() > 0 && !txtPesquisaPeloNome.getText().contains("Nome do paciente")) {
			pesquisaPeloNome = txtPesquisaPeloNome.getText();
			txtPesquisaPeloNome.setText(pesquisaPeloNome);
		} else {
			txtPesquisaPeloNome.setText("");
		}
	}// GEN-LAST:event_txtPesquisaPeloNomeFocusGained

	private void txtPesquisaPeloNomeFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtPesquisaPeloNomeFocusLost
		pesquisaPeloNome = txtPesquisaPeloNome.getText();
		if (pesquisaPeloNome.length() == 0 || txtPesquisaPeloNome.getText().contains("Nome do paciente")) {
			txtPesquisaPeloNome.setText("Nome do paciente");
		}
	}// GEN-LAST:event_txtPesquisaPeloNomeFocusLost

	private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPesquisarActionPerformed
		readTablePeloNome(txtPesquisaPeloNome.getText());
	}// GEN-LAST:event_btnPesquisarActionPerformed

	private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVoltarActionPerformed
		new TelaEscolhaFuncionario().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnVoltarActionPerformed

	public void readTable() {
		DefaultTableModel modelo = (DefaultTableModel) tbAtendimentos.getModel();
		modelo.setNumRows(0);
		AtendimentoDAO aDao = new AtendimentoDAO();

		for (Atendimento a : aDao.readAtendimentos()) {
			modelo.addRow(new Object[] { a.getNome(), a.getDocumento(), DATA_ATENDIMENTO, a.getNumDeConsultas() });
		}
	}

	public void readTablePeloNome(String nome) {
		DefaultTableModel modelo = (DefaultTableModel) tbAtendimentos.getModel();
		modelo.setNumRows(0);
		AtendimentoDAO aDao = new AtendimentoDAO();

		for (Atendimento a : aDao.buscarAtendimento(nome)) {
			modelo.addRow(new Object[] { a.getNome(), a.getDocumento(), DATA_ATENDIMENTO, a.getNumDeConsultas() });
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaListaDeAtendimentos.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			TelaListaDeAtendimentos telaCadastroDeFuncionarios = new TelaListaDeAtendimentos();
			telaCadastroDeFuncionarios.setVisible(true);
			telaCadastroDeFuncionarios.getContentPane().setBackground(new Color(8, 77, 110));
		});
	}

	private javax.swing.JButton btnPesquisar;
	private javax.swing.JButton btnVoltar;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tbAtendimentos;
	private javax.swing.JTextField txtPesquisaPeloNome;
}
