/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marlonenathan.telas;

import java.awt.Color;

import javax.swing.JOptionPane;

import br.com.marlonenathan.model.bean.Funcionario;
import br.com.marlonenathan.model.dao.PessoaDAO;

/**
 *
 * @author marlonmazzine
 */
public class TelaEditarFuncionario extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form TelaCadastraFuncionario
	 */
	public TelaEditarFuncionario() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		txtNome = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtUsuario = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		pswSenha = new javax.swing.JPasswordField();
		btnSalvar = new javax.swing.JButton();
		btnSair = new javax.swing.JButton();
		txtCRM = new javax.swing.JFormattedTextField();
		txtTelefone = new javax.swing.JFormattedTextField();
		txtNascimento = new javax.swing.JFormattedTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Novo cadastro");
		setBackground(new java.awt.Color(8, 77, 110));
		setMaximumSize(new java.awt.Dimension(600, 680));
		setMinimumSize(new java.awt.Dimension(600, 680));
		setPreferredSize(new java.awt.Dimension(600, 680));
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(0, 102, 204));
		jPanel1.setPreferredSize(new java.awt.Dimension(342, 161));

		jLabel5.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Novo cadastro");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(45, 45, 45).addComponent(jLabel5)
						.addContainerGap(269, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(59, 59, 59).addComponent(jLabel5)
						.addContainerGap(65, Short.MAX_VALUE)));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

		jPanel2.setBackground(new java.awt.Color(8, 77, 110));
		jPanel2.setMaximumSize(new java.awt.Dimension(600, 530));
		jPanel2.setMinimumSize(new java.awt.Dimension(600, 530));
		jPanel2.setName(""); // NOI18N

		txtNome.setBackground(new java.awt.Color(204, 204, 204));
		txtNome.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		txtNome.setForeground(new java.awt.Color(51, 51, 51));

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Nome:");

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("CRM:");

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Telefone:");

		jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Nascimento:");

		txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
		txtUsuario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		txtUsuario.setForeground(new java.awt.Color(51, 51, 51));

		jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("Usuário:");

		jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Senha:");

		pswSenha.setBackground(new java.awt.Color(204, 204, 204));
		pswSenha.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
		pswSenha.setForeground(new java.awt.Color(51, 51, 51));

		btnSalvar.setBackground(new java.awt.Color(35, 142, 35));
		btnSalvar.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/checkmark.png"))); // NOI18N
		btnSalvar.setBorderPainted(false);
		btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSalvar.setFocusPainted(false);
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnSair.setBackground(new java.awt.Color(204, 0, 51));
		btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/marlonenathan/imagens/delete.png"))); // NOI18N
		btnSair.setBorderPainted(false);
		btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnSair.setFocusPainted(false);
		btnSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSairActionPerformed(evt);
			}
		});

		txtCRM.setBackground(new java.awt.Color(204, 204, 204));
		txtCRM.setForeground(new java.awt.Color(51, 51, 51));
		try {
			txtCRM.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.#####-#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtCRM.setCaretColor(new java.awt.Color(51, 51, 51));
		txtCRM.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

		txtTelefone.setBackground(new java.awt.Color(204, 204, 204));
		txtTelefone.setForeground(new java.awt.Color(51, 51, 51));
		try {
			txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
					new javax.swing.text.MaskFormatter("(##) # ####-####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtTelefone.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

		txtNascimento.setBackground(new java.awt.Color(204, 204, 204));
		txtNascimento.setForeground(new java.awt.Color(51, 51, 51));
		try {
			txtNascimento.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtNascimento.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 600, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(53, 53, 53).addComponent(jLabel1)
										.addGap(18, 18, 18).addComponent(txtNome,
												javax.swing.GroupLayout.PREFERRED_SIZE, 400,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(64, 64, 64).addComponent(jLabel2)
										.addGap(18, 18, 18).addComponent(txtCRM, javax.swing.GroupLayout.PREFERRED_SIZE,
												400, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(27, 27, 27).addComponent(jLabel3)
										.addGap(18, 18, 18).addComponent(txtTelefone,
												javax.swing.GroupLayout.PREFERRED_SIZE, 400,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel4).addGap(18, 18, 18)
										.addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(38, 38, 38).addComponent(jLabel6)
										.addGap(18, 18, 18).addComponent(txtUsuario,
												javax.swing.GroupLayout.PREFERRED_SIZE, 400,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(50, 50, 50).addComponent(jLabel7)
										.addGap(18, 18, 18).addComponent(pswSenha,
												javax.swing.GroupLayout.PREFERRED_SIZE, 400,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(386, 386, 386)
										.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(btnSair,
												javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 0, Short.MAX_VALUE))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 530, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel1))
										.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel2))
										.addComponent(txtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel3))
										.addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel4))
										.addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel6))
										.addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(15, 15, 15)
												.addComponent(jLabel7))
										.addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 0, Short.MAX_VALUE))));

		txtNascimento.getAccessibleContext().setAccessibleDescription("");

		getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 600, 520));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
		Funcionario f = new Funcionario();
		PessoaDAO dao = new PessoaDAO();

		String senha = new String(pswSenha.getPassword());

		f.setNome(txtNome.getText());
		f.setDocumento(txtCRM.getText());
		f.setTelefone(txtTelefone.getText());
		f.setNascimento(txtNascimento.getText());
		f.setUsuario(txtUsuario.getText());
		f.setSenha(senha);

		if (txtNome.getText().replace("[^0-9]", "").length() == 0
				|| txtCRM.getText().replace("[^0-9]", "").length() == 0 || txtUsuario.getText().isEmpty()
				|| senha.isEmpty() || senha.length() > 10) {
			JOptionPane.showMessageDialog(null,
					"Os campos 'Nome', 'CRM', 'Usuário' e 'Senha' são de preenchimento obrigatório");
		} else {
			dao.updateFuncionario(f);
			new TelaCadastroDeFuncionarios().setVisible(true);
			this.dispose();
		}
	}// GEN-LAST:event_btnSalvarActionPerformed

	private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
		new TelaCadastroDeFuncionarios().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_btnSairActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			TelaEditarFuncionario telaCadastraFuncionario = new TelaEditarFuncionario();
			telaCadastraFuncionario.setVisible(true);
			telaCadastraFuncionario.getContentPane().setBackground(new Color(8, 77, 110));
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSair;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	public javax.swing.JPasswordField pswSenha;
	public javax.swing.JFormattedTextField txtCRM;
	public javax.swing.JFormattedTextField txtNascimento;
	public javax.swing.JTextField txtNome;
	public javax.swing.JFormattedTextField txtTelefone;
	public javax.swing.JTextField txtUsuario;
	// End of variables declaration//GEN-END:variables
}
